openapi: 3.0.0

info:
    title: Lookup for unused rules
    description: Lookup for unused rules in device.
    version: "1.0.1"

servers:
    - url: https://86bd-108-20-176-8.ngrok-free.app/

paths:
    /securetrack/api/rule_search/{deviceId}.json?lasthitgreater:%2030%20rule.isdisabled:false%20action:allow&start=0&count=3:
        get:
            operationId: UnusedRules
            summary: Retrieve unused rules from a device based on the device id.
            parameters:
                -   in: path
                    name: deviceId
                    schema:
                        type: string
                    required: true
                    description: The device id to lookup for unused rules
            responses:
                200:
                    description: Success
                404:
                    description: Value is missing or not valid
    /securetrack/api/rule_search.json?lasthitgreater:%2030%20rule.isdisabled:false%20action:allow:
        get:
            operationId: UnusedRulesPerDevice
            summary: Retrieve unused rule count based on the device id in SecureTrack.
            responses:
                200:
                    description: OK
                404:
                    description: Value is missing or not valid
    /securetrack/api/devices/{deviceId}.json:
        get:
            operationId: UnusedRulesDeviceInformation
            summary: Get device details based on the device id the way it is stored in SecureTrack.
            parameters:
                -   in: path
                    name: deviceId
                    schema:
                        type: string
                    required: true
                    description: The device id to lookup for unused rules
            responses:
                200:
                    description: OK
    /securechangeworkflow/api/securechange/workflows/active_workflows.json?type=RULE_DECOMMISSION:
        get:
            operationId: RuleDecommissionWorkflows
            summary: Rule decommission workflow list for mitigating security issues, such as disabling unused rules.
            responses:
                200:
                    description: OK
                400:
                    description: <TYPE> is not a valid workflow type