openapi: 3.0.0

info:
    title: Lookup for unused rules
    description: Lookup for unused rules in device.
    version: "1.0.1"

servers:
    - url: https://c1a1-108-20-176-8.ngrok-free.app/

paths:
    /securetrack/api/rule_search/{deviceId}.json?lasthitgreater:%2030%20rule.isdisabled:false%20action:allow&start:0&count:10:
        get:
            operationId: UnusedRules
            summary: Retrieve all unused rules from a device
            parameters:
                -   in: path
                    name: deviceId
                    schema:
                        type: string
                    required: true
                    description: The device id to lookup for unused rules
            responses:
                200:
                    description: Success
                404:
                    description: Value is missing or not valid
    /securetrack/api/rule_search.json?lasthitgreater:%2030%20rule.isdisabled:false%20action:allow:
        get:
            operationId: UnusedRulesPerDevice
            summary: Unused rule count per device
            responses:
                200:
                    description: OK
                404:
                    description: Value is missing or not valid
    /securetrack/api/devices/{deviceId}.json:
        get:
            operationId: GetDevices
            summary: Get all devices
            parameters:
                -   in: path
                    name: deviceId
                    schema:
                        type: string
                    required: true
                    description: The device id to lookup for unused rules
            responses:
                200:
                    description: OK
