openapi: 3.0.0

info:
    title: Get unused rules using TOS
    description: Get unused rules using TOS.
    version: 1.0.0

servers:
    - url: https://86bd-108-20-176-8.ngrok-free.app/

paths:
    /securetrack/api/rule_search.json:
        get:
            operationId: UnusedRules
            summary: Retrieve unused rule count based on the device id in SecureTrack.
            parameters:
                -   $ref: '#/components/parameters/searchText'
            responses:
                200:
                    description: List of devices with rule count
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    device_list:
                                        type: object
                                        properties:
                                            device:
                                                type: array
                                                items:
                                                    properties:
                                                        device_id:
                                                            type: integer
                                                        revision_id:
                                                            type: integer
                                                        rule_count:
                                                            type: integer
                400:
                    description: Value is missing or not valid
    /securetrack/api/rule_search/{deviceId}.json:
        get:
            operationId: UnusedRulesPerDevice
            summary: Retrieve unused rules from a device based on the device id.
            parameters:
                -   in: path
                    name: deviceId
                    required: true
                    description: The device id to lookup for unused rules
                    schema:
                        type: integer
                -   $ref: '#/components/parameters/searchText'
                -   $ref: '#/components/parameters/start'
                -   $ref: '#/components/parameters/count'
            responses:
                200:
                    description: Return object of unused rules
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    rules:
                                        type: object
                                        properties:
                                            count:
                                                type: integer
                                            total:
                                                type: integer
                                            rule:
                                                type: array
                404:
                    description: Value is missing or not valid
    /securetrack/api/devices/{deviceId}.json:
        get:
            operationId: UnusedRulesDeviceInformation
            summary: Get device details based on the device id the way it is stored in SecureTrack.
            parameters:
                -   in: path
                    name: deviceId
                    required: true
                    description: The device id to lookup for unused rules
                    schema:
                        type: string
            responses:
                200:
                    description: OK
    /securechangeworkflow/api/securechange/workflows/active_workflows.json:
        get:
            operationId: RuleDecommissionWorkflows
            summary: Rule decommission workflow list for mitigating security issues, such as disabling unused rules.
            parameters:
                -   in: query
                    name: type
                    required: true
                    schema:
                        type: string
                        default: RULE_DECOMMISSION
            responses:
                200:
                    description: OK
                400:
                    description: <TYPE> is not a valid workflow type

components:
    parameters:
        searchText:
            in: query
            name: search_text
            required: true
            schema:
                type: string
                default: 'lasthitgreater:30 rule.isdisabled:false action:allow'
        start:
            in: query
            name: start
            required: true
            schema:
                type: integer
                default: 0
                minimum: 0
        count:
            in: query
            name: count
            required: true
            schema:
                type: integer
                default: 3
                minimum: 3
                maximum: 10